name: validate-test-cases

on:
  push:
    branches: ['master']
    paths:
      - 'functest/**'
  pull_request:
    paths:
      - 'functest/**'

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  protolint:
    name: protolint for grpc-crud
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run linter
        uses: ci-space/protolint-action@master
        with:
          dir: functest
          config_path: functest/protolint.yaml
